# Generated by Django 6.0 on 2026-02-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_PROFILE', 'Pending Profile Setup'), ('PENDING_APPROVAL', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_PROFILE', max_length=20),
        ),
    ]
