# Generated by Django 6.0 on 2026-02-02 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Legal name of the organization', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL identifier', max_length=255, unique=True)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('org_code', models.CharField(help_text='Unique code for internal reference', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#ec4899', max_length=7)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pan_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('ai_summary', models.JSONField(blank=True, default=dict, help_text='AI-generated summary of the organization state/stats.')),
            ],
            options={
                'indexes': [models.Index(fields=['domain_name'], name='Org_organiz_domain__24ea60_idx'), models.Index(fields=['slug'], name='Org_organiz_slug_555bfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('LICENSE', 'License'), ('REGISTRATION', 'Registration Certificate'), ('SOP', 'Standard Operating Procedure'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], max_length=50)),
                ('file_url', models.URLField(help_text='External storage URL (S3)')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active_version', models.BooleanField(default=True)),
                ('ai_extracted_text', models.TextField(blank=True, help_text='OCR or text extraction for search')),
                ('embedding_id', models.UUIDField(blank=True, help_text='Reference to vector DB embedding', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='Org.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CAMPUS', 'Campus'), ('BRANCH', 'Branch'), ('DEPT', 'Department')], default='BRANCH', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_legal_entity', models.BooleanField(default=False, help_text='Does this branch have its own legal registration?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='Org.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Org.suborganization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
