# Generated by Django 6.0 on 2026-02-05 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(help_text='Unique URL identifier', max_length=255, unique=True)),
                ('org_code', models.CharField(help_text='Unique code for internal reference', max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='org_logos/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#ec4899', max_length=7)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pan_vat_number', models.CharField(max_length=50)),
                ('established_date', models.DateField()),
                ('ai_summary', models.JSONField(default=dict, help_text='AI-generated summary of the organization state/stats.')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='Org_organiz_slug_555bfa_idx',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='org_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='gmail',
            field=models.EmailField(default='default@example.com', help_text='primary gmail of organization', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Org.organization'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='pan_vat_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='organizationprofile',
            index=models.Index(fields=['slug'], name='Org_organiz_slug_c1b300_idx'),
        ),
    ]
