# Generated by Django 6.0 on 2026-01-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='pan_vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='theme_color_primary',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='theme_color_secondary',
            field=models.CharField(default='#ec4899', max_length=7),
        ),
    ]
